[workspace]
members = [
    "custom-game-randomizer",
    "client-api",
    "custom-game-creator",
    "lol-utilities",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
# panic = "abort"
