[package]
name = "lol-custom-game-randomizer"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
client-api = { path = "../client-api" }
