[package]
name = "custom-game-creator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
client-api = { version = "0.1.0", path = "../client-api" }
eyre = "0.6.8"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
